version: '3'

tasks:
  # Build everything
  build:
    desc: Build all binaries (runner, daemon, imgbuilder)
    deps: [runner, daemon, imgbuilder]

  # Build the runner binary (static, linux)
  runner:
    desc: Build the runner binary (static Linux binary)
    cmds:
      - go build -o bin/runner ./cmd/runner
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    sources:
      - cmd/runner/**/*.go
      - protocol/**/*.go
    generates:
      - bin/runner

  # Build daemon
  daemon:
    desc: Build the sandkasten daemon
    cmds:
      - go build -o bin/sandkasten{{exeExt}} ./cmd/sandkasten
    sources:
      - cmd/sandkasten/**/*.go
      - cmd/imgbuilder/**/*.go
      - internal/**/*.go
      - protocol/**/*.go
    generates:
      - bin/sandkasten{{exeExt}}

  # Build imgbuilder tool
  imgbuilder:
    desc: Build the image builder tool
    cmds:
      - go build -o bin/imgbuilder{{exeExt}} ./cmd/imgbuilder
    sources:
      - cmd/imgbuilder/**/*.go
      - internal/**/*.go
    generates:
      - bin/imgbuilder{{exeExt}}

  # Build sandkasten-wsl Windows helper (run daemon inside WSL2)
  sandkasten-wsl:
    desc: Build sandkasten-wsl.exe for Windows (helper to run daemon in WSL2)
    cmds:
      - go build -o bin/sandkasten-wsl.exe ./cmd/sandkasten-wsl
    env:
      GOOS: windows
      GOARCH: amd64
    sources:
      - cmd/sandkasten-wsl/**/*.go
    generates:
      - bin/sandkasten-wsl.exe

  # Run the daemon (assumes already built)
  run:
    desc: Run the daemon locally (requires sudo on Linux)
    cmds:
      - sudo ./bin/sandkasten{{exeExt}} --config ./sandkasten.yaml

  # Build and run daemon (development)
  dev:
    desc: Build and run daemon for development
    deps: [daemon]
    cmds:
      - sudo ./bin/sandkasten{{exeExt}} --config ./sandkasten-dev.yaml

  # Run unit tests
  test:
    desc: Run all unit tests
    cmds:
      - go test ./... -v -count=1

  # Run unit tests with race detector
  test-race:
    desc: Run all unit tests with race detector
    cmds:
      - go test ./... -v -race -count=1

  # Run E2E integration tests (requires Linux + images)
  test-e2e:
    desc: Run integration tests (requires running on Linux with images)
    cmds:
      - go test -v -count=1 -tags=linux,integration -timeout=5m ./tests/integration/...

  # Generate coverage report
  test-cover:
    desc: Generate test coverage report
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out

  # Clean build artifacts
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/* coverage.out
